repos:
- repo: local
  hooks:
  - id: MyTests
    name: Run my tests
    entry: python
    language: system
    args: [pre_commit_test.py]
  - id: MyCommitMsg
    name: Run my commit msg
    entry: python
    language: system
    args: [commit_msg.py]
    stages: [commit-msg]